env: {browser: true, es6: true, jest/globals: true, node: true}
extends: [airbnb, plugin:jest/recommended]
parser: babel-eslint
parserOptions:
  ecmaFeatures: {jsx: true}
  ecmaVersion: 6
  sourceType: module
plugins: [import, react, jsx-a11y, jest, json]
rules:
  import/extensions:
  - 1
  - {js: never}
  import/first:
  - 2
  - {absolute-first: 'off'}
  import/no-extraneous-dependencies: 'off'
  import/no-named-as-default: 'off'
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/valid-expect: error
  jsx-a11y/no-noninteractive-element-interactions: 'off'
  react/jsx-filename-extension:
  - 1
  - extensions: [.js, .jsx]
  react/jsx-indent-props: [2, 2]
  react/react-in-jsx-scope: 'off'
  react/require-default-props: 'off'
settings:
  import/resolver:
    node: {moduleDirectory: .}
    webpack: {config: ./config/webpack.prod.js}
