language: node_js
node_js:
  - "node"
script:
  - yarn test
  - yarn cover
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
branches:
  only:
    - master
cache:
  yarn: true
  directories:
  - node_modules
addons:
  code_climate:
    repo_token: 373467d1f4b63d79649cb8dc66269b1ea29d5245c49660d4653690334fbfce42